FROM debian:jessie

MAINTAINER Pascal MARTIN <contact@pascal-martin.fr>

# Si notre 'php' avait été compilé avec un peu plus d'extensions, il aurait très probablement besoin
# de quelques bibliothèques système pour pouvoir s'exécuter ;-)
# RUN apt-get update && apt-get install -y ... && apt-get clean
